# Generated by Django 4.2.2 on 2023-06-21 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artists',
            options={'ordering': ['-time_create'], 'verbose_name': 'Художники', 'verbose_name_plural': 'Известные Художники'},
        ),
        migrations.AlterField(
            model_name='artists',
            name='title',
            field=models.CharField(max_length=250, verbose_name='Заголовок'),
        ),
    ]
